---
exclude_paths:
  - test

detectors:
  DuplicateMethodCall:
    exclude:
    - QueryService::WikidataDate#<=>
  MissingSafeMethod:
    exclude:
    - WikidataPositionHistory::PageRewriter
  UncommunicativeVariableName:
    exclude:
    - QueryService::Query#results
