AllCops:
  Exclude:
    - 'Vagrantfile'
    - 'vendor/**/*'
  TargetRubyVersion: 2.4
  NewCops: enable

inherit_from:
  - .rubocop_todo.yml

Layout/HashAlignment:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table

Layout/LineLength:
  Max: 150

Lint/AssignmentInCondition:
  Enabled: false

Naming/ClassAndModuleCamelCase:
  Enabled: false

Style/CollectionMethods:
  Enabled: true

Style/Documentation:
  Enabled: false

Style/FormatString:
  EnforcedStyle: percent

Style/FormatStringToken:
  Enabled: false

Style/HashSyntax:
  EnforcedStyle: ruby19_no_mixed_keys

Style/RescueModifier:
  Enabled: false

Style/SymbolArray:
  Enabled: true

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma
